### ISSUE TITLE
Allow to return values when called programmatically

### ISSUE THREAD

**Issue by bcherrington** [thbar/kiba#12]
It would be great to be able to return parameters back from the ETL script. 

An example of a usefuly return value would be the number of rows processed.

**Comment by thbar** [comment]
Hi @bcherrington! You can achieve that using a `post_process` block like this:

``` ruby
require 'json'

class EnumerableSource
  def initialize(enumerable)
    @enumerable = enumerable
  end

  def each
    @enumerable.each do |row|
      yield row
    end
  end
end

row_count = 0

source EnumerableSource, (1..100_000)

# no-op transform, just counting
# note that it will count differently based on where in the pipeline you place it!
transform do |row|
  row_count += 1
  row
end

post_process do
  puts({ rows_processed: row_count }.to_json)
end
```

Be sure to check out the exit code too, if called programmatically :P!

You could also inject the output into a file that you would delete initially etc.

Is that good enough for you, or are there scenarios where this would not work?

Note that I'm not opposed to adding stuff to Kiba, I'm just always trying very hard to keep the codebase uncluttered and try to provide tools to implement techniques, rather than the techniques themselves, since this is what made activewarehouse-etl harder and harder to maintain.

Let me know what you think!

**Comment by thbar** [comment]
@bcherrington let me know if what I suggested works for you :-)

**Comment by bcherrington** [comment]
Hi @thbar,

I am using the Kiba library within a Rails application we are developing to provide a dashboard for a backup system. I am using Sidekiq (a job processor) to periodically process jobs including Kiba ETL scripts. 

I have written a few generic ETL scripts which take a table name as an input parameter and then import the data from the backup system to a local database. 

The Kiba ETL scripts are being called from the application and not a cli.

The approach you have suggest to output data would work fine for running the script from the cli but is less elegant (in my opinion) when calling it from an application.

I was looking to be able to provide return results such as, the number of rows processed, the last primary key value, or an array of warnings and errors which occurred when writing the data to the destination, etc. It is like that I would want to return multiple of these values back to the calling application in a hash or array.

Thanks,

Bruce

**Comment by thbar** [comment]
@bcherrington oh I see - I definitely understand now. Let me think about that, I think we will probably be able to find something that works nicely in that case. I'll get back to you here.

**Comment by thbar** [comment]
Stale issue - I've been investigating a bit more on the consequences of calling Kiba from Sidekiq and it's not crystal clear yet. Closing for now!

**Comment by thbar** [comment]
Just wanted to update this, since Kiba v2 is out and officially supports a [programmatic API](https://github.com/thbar/kiba/wiki/Considerations-for-running-Kiba-jobs-programmatically-%28from-Sidekiq%2C-Faktory%2C-Rake%2C-...%29) allowing to issue calls from Rake, Sidekiq etc.

This means that it's much easier to grab "out" values or refer to actual variables, without any CLI invocation.

Not sure if you're still using Kiba or not, but heads-up @bcherrington just in case!
