### ISSUE TITLE
Full vs. Incremental Loading

### ISSUE THREAD

**Issue by amigotune** [thbar/kiba#24]
Hi!

Kiba works with both full and incremental loads? Where can I find more information about this?

Cheers!

**Comment by thbar** [comment]
You can do both, Kiba doesn't enforce anything specific with regard to this. There isn't documentation on that yet since it is very case-dependent, but I'll come back later to give you more ideas.

Can you open the question over at [StackOverflow](http://stackoverflow.com/questions/ask?tags=kiba-etl), I'll reply over there? Thanks!

**Comment by amigotune** [comment]
Thibaut! I opened the question here:
http://stackoverflow.com/questions/34699881/kiba-incremental-sync-between-tables

Cheers!

On Fri, Jan 8, 2016 at 2:05 PM, Thibaut Barrère notifications@github.com
wrote:

> Closed #24 https://github.com/thbar/kiba/issues/24.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thbar/kiba/issues/24#event-509563954.

ᐧ
