### ISSUE TITLE
Execution lists

### ISSUE THREAD

**Issue by germs12** [thbar/kiba#26]
Hi,

First off thank you so much for your hard work on Kiba.  It's a wonderful tool that's making my life a lot easier.  I am wondering if there is a way to write a bunch of ETL modules and then define the order that they are run?

Example: I have 3 different tables that are being transformed into 5 tables.  I have a specific order I need to run them in production, but while developing them I can do each table 1 at a time.  I would like it if I could define a run list that executes them in a specific order.  Thoughts?  Thanks!

**Comment by thbar** [comment]
Hey there - glad Kiba is useful to you :smile:

My recommendation for sequences is to invoke kiba yourself from a rake task or a bash script with `set -e`, or even from a "macro" kiba job if you prefer.

This is what gives you the most flexibility since you can do pretty much anything you want.

Example:

``` ruby
my_tables = %w[products orders]
my_tables.each do |table|
  system! "MY_TABLE=#{table} bundle exec kiba my_job.etl"
end
```

with:

``` ruby
def system!(command)
  fail "Command #{command} failed!" unless system(command)
end
```

Or:

``` bash
set -e # fail fast
bundle exec kiba first_job.etl
bundle exec kiba second_job.etl
```

Or same in a Rake task if you prefer.

This "lack of feature" on batch handling is actually a conscious design decision (based on my previous experience maintaining activewarehouse-etl, which supported batches): this leaves you with the possibility to handle very complex or specific ways to process batches (like: reporting in a database before each step, using parallel calls with a unix command etc etc), since you have full control.

Hope this helps, and let me know if this isn't clear or you need more help.

**Comment by germs12** [comment]
You're a beast!  Thank you so much @thbar

**Comment by thbar** [comment]
@germs12 you welcome! Thanks for asking. I'm adding this to the upcoming Kiba cookbook #29.
